# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jacob.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bjacob.proto\x12\x05jacob\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x12HelloRequestStream\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x83\x01\n\x07Greeter\x12\x34\n\x08SayHello\x12\x13.jacob.HelloRequest\x1a\x11.jacob.HelloReply\"\x00\x12\x42\n\x0eSayHelloStream\x12\x19.jacob.HelloRequestStream\x1a\x11.jacob.HelloReply\"\x00\x30\x01\x42\'\n\x1bio.grpc.examples.helloworldB\x00P\x01\xa2\x02\x03HLWb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREQUESTSTREAM = DESCRIPTOR.message_types_by_name['HelloRequestStream']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'jacob_pb2'
  # @@protoc_insertion_point(class_scope:jacob.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloRequestStream = _reflection.GeneratedProtocolMessageType('HelloRequestStream', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUESTSTREAM,
  '__module__' : 'jacob_pb2'
  # @@protoc_insertion_point(class_scope:jacob.HelloRequestStream)
  })
_sym_db.RegisterMessage(HelloRequestStream)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'jacob_pb2'
  # @@protoc_insertion_point(class_scope:jacob.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\000P\001\242\002\003HLW'
  _HELLOREQUEST._serialized_start=22
  _HELLOREQUEST._serialized_end=50
  _HELLOREQUESTSTREAM._serialized_start=52
  _HELLOREQUESTSTREAM._serialized_end=86
  _HELLOREPLY._serialized_start=88
  _HELLOREPLY._serialized_end=117
  _GREETER._serialized_start=120
  _GREETER._serialized_end=251
# @@protoc_insertion_point(module_scope)
